function [scenario, egoVehicle] = driving_scenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 04-Feb-2022 17:32:12

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [74.1 -56.3 0;
    313 12 0;
    306 -119 10;
    241 -9.5 0;
    107.2 102.8 0;
    79.6 26.3 0;
    74.1 -56.3 0];
laneSpecification = lanespec(3);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [238.853998203635 -0.229566982212093 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [239.753998203635 -0.729566982212091 0.01;
    248 -40.4 1.4;
    260.7 -77.6 5.4;
    279.5 -104.3 8.6;
    298.7 -116.8 9.9;
    316.9 -122.2 9.9;
    333 -121.9 9.6;
    351.2 -115.3 8.9;
    368.1 -102.4 8;
    380.5 -84.4 6.7;
    385.9 -58.9 4.9;
    379.7 -30.3 3.1;
    364.2 -9.10000000000001 1.5;
    328.4 9.99999999999999 0.1;
    302.3 9.99999999999999 0;
    261.8 -5.20000000000001 0;
    204.7 -52 0;
    163.5 -78.6 0;
    136.76 -86.22 0.01;
    110.93 -84.35 0.01;
    90.1 -74.72 0.01;
    73.1 -53.4 0;
    69.7 -20.3 0;
    78.5 17.2 0;
    95.3 84.6 0;
    121 110.7 0;
    170.8 112.4 0;
    209.5 82.5 0;
    232.1 33.4 0;
    241.42 -6.47000000000001 0.01];
speed = [5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5];
trajectory(egoVehicle, waypoints, speed);

