name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Enderfga
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_code_visibility: public
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers
          plugin_repositories: yes
          plugin_repositories_featured: Enderfga/claw-orchestrator, Alpha-VLLM/LLaMA2-Accessory, NVlabs/AnyFlow
          plugin_repositories_pinned: 0
          plugin_repositories_starred: 0
          plugin_repositories_random: 0
          plugin_repositories_affiliations: owner
